### ISSUE TITLE
Add option to limit amount of dumped documents

### ISSUE THREAD

**Issue by Pczek** [taskrabbit/elasticsearch-dump#234] opened 2016-06-24 17:31 UTC
We currently have a huge elasticsearch cluster with 3TB content. I want to create a smaller version for local use. The --offset option let's me skip a certain amount of documents, but when i just want a certain amount of document I have to provide a specific amount of documents to skip with this option.

It would be way easier if i could just specify how many documents I want to dump in total.
maybe call it `--total` or `--max`

`elasticsearch --input es1 --ouput es2 --max 1000`

And btw I'am currently trying to use the workaround using the --offset option. It is extremely slow. I have an offset of 550 mio documents to just dump the last 5 mio but it seems it's stuck in the offset phase. Shouldn't doing this offset be almost instant?

**Comment by evantahler** [comment] 2016-06-24 18:24
duplicate of https://github.com/taskrabbit/elasticsearch-dump/issues/224

**Comment by evantahler** [comment] 2016-06-24 18:26
You point out an important nuance not captured in the previous story: Yes, you can use `--offest` to accomplish what you want, but right now, `--offset` only effects the writer, not the reader.  To that end, you are still "Getting" the first N results from your cluster, but just not sending them anywhere.  

If you could modify the `elasticsearch` transport's behavior when getting data to also skip the offset, this would speed things up.  

Let me know if you need help getting started with that pull request!

**Comment by flybd5** [comment] 2016-09-21 15:00
Can you use the bulk API in ES to grab the slice of the index you want, download it and then delete it? Just a thought...

**Comment by evantahler** [comment] 2016-09-21 16:13
Remember you can also send arbitrary `query` with your `--input` request as well

**Comment by aendrew** [comment] 2017-02-10 11:11
My index is about 33M records and I've been running into issues importing it all at once. My use-case is fairly simple, just a bunch of static documents stored that aren't accessible to anyone but me at the moment. I've currently worked around it by dumping to a file, using `split -n 1000000` to split that dump into 1M chunks, then importing those sequentially. The fact that elasticdump outputs purely as ndjson (AFAICT, anyhow) and doesn't include the bulk instruction part of the request in the dump makes things much easier. 😄

**Comment by victorssilva** [comment] 2017-06-23 15:33
Looking into it

**Closed** 2018-10-04 17:43 UTC
Labels: type: enhancement
