### ISSUE TITLE
ES URL parsing assumes it is at too

### ISSUE THREAD

**Issue by kjvalencik** [taskrabbit/elasticsearch-dump#127] opened 2015-09-24 13:59 UTC
The following portion of code assumes that if there are at least two slahes then a `type` has been provided. This is not necessarily true if ES is being proxied to a different directory.

https://github.com/taskrabbit/elasticsearch-dump/blob/c8541b0242b877b4ce543c2ab8d5df0724a2aa63/lib/transports/elasticsearch.js#L322

It would be helpful if this behavior could be disabled in someway or if you could explicitly provide the ES root.

If you have a preference on how the parameters for this would look I can provide a PR. Maybe if you provide index and type as flags, skip URL parsing. Thanks!

Example: This is what an ES URL looks like when proxied through kuberetes

`http://localhost:8001/api/v1/proxy/namespaces/default/services/elasticsearch/_cat/indices`

**Comment by evantahler** [comment] 2015-09-24 17:34
this is a duplicate of https://github.com/taskrabbit/elasticsearch-dump/issues/121.  I'll close this issue, but please head on over to https://github.com/taskrabbit/elasticsearch-dump/issues/121 and carry on the conversation there.

**Closed by evantahler** 2015-09-24 17:34 UTC
