### ISSUE TITLE
elasticdump fails after 15gig and --offset doesn't allow to continue with ES 7.2.0

### ISSUE THREAD

**Issue by tombburnell** [taskrabbit/elasticsearch-dump#624] opened 2019-10-14 14:51 UTC
I just created this ticket but it was closed quickly- I presume because I forgot to add a title. If you close this one too please let me know why.

- ElasticDump version  - 6.8.2
- Elasticsearch version - 7.2.0
- Node.js version - 12.10
- Full command you are having issue with (with inputs and outputs)

 **node ./node_modules/.bin/elasticdump --input=http://localhost:9301 --output=/data/myindex/myindex.json --fileSize=10mb**

After downloading for 3 hrs it stopped with the following error.

```
Fri, 11 Oct 2019 14:48:14 GMT | Error Emitted => {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [16347185302/15.2gb], which is larger than the limit of [16249153126/15.1gb], real usage: [16347168248/15.2gb], new bytes reserved: [17054/16.6kb]","bytes_wanted":16347185302,"bytes_limit":16249153126,"durability":"PERMANENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [16347185302/15.2gb], which is larger than the limit of [16249153126/15.1gb], real usage: [16347168248/15.2gb], new bytes reserved: [17054/16.6kb]","bytes_wanted":16347185302,"bytes_limit":16249153126,"durability":"PERMANENT"},"status":429}
Fri, 11 Oct 2019 14:48:14 GMT | Total Writes: 12443900
Fri, 11 Oct 2019 14:48:14 GMT | dump ended with error (get phase) => Error: {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [16347185302/15.2gb], which is larger than the limit of [16249153126/15.1gb], real usage: [16347168248/15.2gb], new bytes reserved: [17054/16.6kb]","bytes_wanted":16347185302,"bytes_limit":16249153126,"durability":"PERMANENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [16347185302/15.2gb], which is larger than the limit of [16249153126/15.1gb], real usage: [16347168248/15.2gb], new bytes reserved: [17054/16.6kb]","bytes_wanted":16347185302,"bytes_limit":16249153126,"durability":"PERMANENT"},"status":429}
```

Then, when attempting to restart with offset it failed due to from/scroll incompatibility.

 **node ./node_modules/.bin/elasticdump --input=http://localhost:9301 --output=/data/myindex/myindex.json --fileSize=10mb --offset 12443800**

```
Mon, 14 Oct 2019 14:27:40 GMT | starting dump
Mon, 14 Oct 2019 14:27:40 GMT | Warning: offsetting 12443800 rows.
Mon, 14 Oct 2019 14:27:40 GMT |   * Using an offset doesn't guarantee that the offset rows have already been written, please refer to the HELP text.
Mon, 14 Oct 2019 14:27:40 GMT | Error Emitted => {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"},"status":400}
Mon, 14 Oct 2019 14:27:40 GMT | Total Writes: 0
Mon, 14 Oct 2019 14:27:40 GMT | dump ended with error (get phase) => Error: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"},"status":400}

```

**Comment by ferronrsmith** [comment] 2019-10-14 14:55
duplicate of #623

**Closed by ferronrsmith** 2019-10-14 14:55 UTC
