### ISSUE TITLE
SyntaxError: Unexpected token <     at Object.parse (native)

### ISSUE THREAD

**Issue by zephyr-hut** [taskrabbit/elasticsearch-dump#301] opened 2017-03-27 13:39 UTC
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 3.10
- Elasticsearch version 5.1.1
- The full command is :-  docker run --rm -ti taskrabbit/elasticsearch-dump --input=http://172.20.1.157:9200/supstore --output=http://url/new/elasticsearch/supstore --type=mapping
It is mapped to a nginx proxy. I have used nginx to move index from one cluster to another and it has always worked.  

The error message is :- 

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:43:21)
    at Request.self.callback (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)

**Comment by evantahler** [comment] 2017-03-27 18:08
duplicate of https://github.com/taskrabbit/elasticsearch-dump/issues/289

**Closed by evantahler** 2017-03-27 18:08 UTC
